### ISSUE TITLE
can't compile v0.9_p20180522 in gentoo using gcc-7.3.0-r3

### ISSUE THREAD

**Issue by rpolasek** [pstavirs/ostinato#267] opened 2018-06-28 04:28 UTC
mld.cpp: In function ‘constexpr T qbswap(T) [with T = long unsigned int]’:
mld.cpp:29:27: error: call to non-constexpr function ‘T qbswap(T) [with T = long long unsigned int]’
     return qbswap<quint64>(quint64(source));
            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
make[1]: *** [Makefile.ostproto:1374: mld.o] Error 1

**Comment by pstavirs** [comment] 2018-06-28 12:19
Duplicate of #265 

Unfortunately, I'm not able to repro the problem in my environment, so if you can help with debug in the failing environment, that'd be great!

**Closed by pstavirs** 2018-06-28 12:19 UTC
