### ISSUE TITLE
Bad TCP checksum

### ISSUE THREAD

**Issue by sharmag2** [pstavirs/ostinato#210] opened 2017-03-08 12:15 UTC
I am trying to generate tcp syn packets with randon src and dst port, However I get Bad TCP checksum in capture file.

**Comment by pstavirs** [comment] 2017-03-08 14:56
Any random pattern will cause a bad checksum. You can either use increment/decrement instead of random or if you need to use random override the checksum to value 0 (which means no checksum computed by sender, so receiver should not verify)

Duplicate of #51

**Closed by pstavirs** 2017-03-08 14:56 UTC
Labels: duplicate
