### ISSUE TITLE
Ostinato VM traffic ports becomes unavailable sometimes

### ISSUE THREAD

**Issue by jimitsalvi** [pstavirs/ostinato#244] opened 2018-01-12 18:30 UTC
After 2 days, the ostinato traffic ports becomes unreachable from GUI.

can reach the windows server from the VM & vice versa.
![1](https://user-images.githubusercontent.com/22686023/34889294-7b7cc93a-f79b-11e7-8174-f5923b21e25f.PNG)
![2](https://user-images.githubusercontent.com/22686023/34889444-fe91f7e6-f79b-11e7-8379-a5c104aa4f74.PNG)
![3](https://user-images.githubusercontent.com/22686023/34889621-aa3cff32-f79c-11e7-82ee-87691b5a1905.PNG)

**Comment by pstavirs** [comment] 2018-01-13 06:01
@jimitsalvi From the images, I'm assuming the IP address of the VM image is 192.168.32.137? And from the Windows GUI the 192.168.32.137 portgroup shows as _connecting_ (yellow/orange status), but on logging into the VM you see local portgroup 127.0.0.1 as _connected_ (green status). Please confirm. Also, does the Windows GUI ever show the port group status as _disconnected_ (red status) or it always _connecting_ (yellow/orange) after it becomes unavailable?

**Comment by jimitsalvi** [comment] 2018-01-13 17:05
Ostinato VM : 192.168.32.137
Windows server : .32.36

Yes, that is correct, on the Ostinato Vm the ports are up but these ports were unreachable for 5-10 mins from the windows GUI. 

As soon as I saw the traffic ports were down, couple of try's doing disconnect and connect the same ports and the port came up after couple of minutes (no reboot of VM required). I did not gather all the data points since I was press on time.

**Comment by pstavirs** [comment] 2018-01-15 12:55
@jimitsalvi Need answer to the below question to be able to proceed on this -
Does the Windows GUI ever show the port group status as disconnected (red status) or it always connecting (yellow/orange) after it becomes unavailable?

**Comment by jimitsalvi** [comment] 2018-01-15 14:40
@pstavirs - From what I remember it was yellow/orange.

**Comment by jimitsalvi** [comment] 2018-01-15 16:33
@pstavirs - After rebooting the VM, it was try to connect (yellow/orange) after which it went red.
Also for one VM is shows as green but no traffic port shows up.

**Comment by jimitsalvi** [comment] 2018-01-15 16:37
@pstavirs  - Yes, it does go to red from yellow in one instance.
![1](https://user-images.githubusercontent.com/22686023/34952637-681b3a08-f9e8-11e7-80d6-e78c8f622bae.PNG)
![2](https://user-images.githubusercontent.com/22686023/34952640-6959e9a0-f9e8-11e7-93af-4de608b8111f.PNG)

**Comment by pstavirs** [comment] 2018-01-16 13:17
@jimitsalvi Since I can't reproduce this issue, you need to help debug this on your side by running a Wireshark capture for TCP port 7878 on both sides when you see the problem. That is the port on which the GUI controller and drone agent talk. You need to see what is happening to those packets *during the time when you face disconnection*

**Comment by jimitsalvi** [comment] 2018-01-16 14:24
Sure.. I will keep you posted.

**Comment by pstavirs** [comment] 2018-05-09 15:58
Packet captures not received from submitter. Closing.

**Closed by pstavirs** 2018-05-09 15:58 UTC
