### ISSUE TITLE
can't save/open stream on Ubuntu

### ISSUE THREAD

**Issue by asdfljdasflkjwfd** [pstavirs/ostinato#166] opened 2015-11-19 03:03 UTC
The file browser only shows /home/ directory and nothing else, can't change directory or save

**Comment by pstavirs** [comment] 2015-11-20 13:11
I can't reproduce the problem on my Ubuntu.

I would suggest you post on the mailing list which has many more eyeballs and people who can help you including myself. Typically, it is better to post on the mailing list first for a discussion and confirmation about a valid bug before filing it on the issue tracker.

For now am closing this issue, but if we do identify this as a bug based on the conversation on the mailing list, I'll reopen.

**Closed** 2015-11-20 13:37 UTC
