### ISSUE TITLE
Ostinato crashes right after start if tun interface is present

### ISSUE THREAD

**Issue by patVog** [pstavirs/ostinato#310] opened 2020-06-15 10:11 UTC
If a tun interface is present at start of ostinato it will crash. 

System: Ubuntu 20.04
Version: Ostinato 1.0 rev

Steps to reproduce:
Create tun interface:  sudo openvpn --mktun --dev tun22
Start ostinato: Now there should be an error message.

**Comment by pstavirs** [comment] 2020-06-17 15:42
Duplicate of #298

**Closed by pstavirs** 2020-06-17 15:42 UTC
