### ISSUE TITLE
Feature Request : Ability to add description for the traffic ports in GUI

### ISSUE THREAD

**Issue by jimitsalvi** [pstavirs/ostinato#247] opened 2018-01-15 15:37 UTC
It would be a good feature to be able to add description to the traffic ports in the GUI since this would help to identify the ports from the GUI. This will definitely help when using/managing multiple VMs.

**Comment by burren-m** [comment] 2018-02-07 15:24
same as #223 ?

**Comment by pstavirs** [comment] 2018-02-09 12:49
Duplicate of #223

**Closed by pstavirs** 2018-02-09 12:49 UTC
