### ISSUE TITLE
Disabling traffic stream takes 3-3.5 mins

### ISSUE THREAD

**Issue by jimitsalvi** [pstavirs/ostinato#243] opened 2018-01-11 19:34 UTC
Disabling a traffic stream and applying it takes 3-3.5 mins during this time the GUI becomes unresponsive.
Same issue observed with duplicating disabled traffic item.

Steps to reproduce:
All steps to be done from main GUI.

1) disable traffic item and click apply- gui freezes for ~3 mins
2) duplicate the same disabled traffic item and click apply- gui freezes for ~3 mins
3) delete the duplicated traffic and click apply - gui freezez for ~ 3 mins.
3) enable the traffic item and click apply- no issue observed
4) duplicate the same enabled traffic item and click apply - no issue observed.
6) delete the duplicated traffic and click apply - no issue observed.

**Comment by pstavirs** [comment] 2018-01-13 05:53
@jimitsalvi How many streams do you have before you disable one or more of them that takes time? Does this stream have some special configuration to be able to reproduce this? I was not able to reproduce this by creating a single default stream.

**Comment by jimitsalvi** [comment] 2018-01-13 16:57
The issue is not dependent on the number of streams. I am seeing this issue even with one traffic stream. No special configuration just simple IPV4 traffic with MTU9210.

**Comment by pstavirs** [comment] 2018-01-15 12:56
@jimitsalvi Please share the stream to recreate this issue

**Comment by jimitsalvi** [comment] 2018-01-15 14:41
Sent

**Comment by pstavirs** [comment] 2018-01-16 13:38
@jimitsalvi Unable to repro problem with the streams in .ostm file

**Comment by jimitsalvi** [comment] 2018-01-16 14:25
Maybe I can show it to you on my setup?

**Comment by pstavirs** [comment] 2018-01-18 13:19
@jimitsalvi Please collect and attach console log for drone. Assuming you are using the Virtual Appliance, follow these steps on the VM -
* Close Ostinato GUI 
* kill the drone process (the process maybe called as bootlocal instead of drone)
* start drone and redirect output to a file
* Repro the issue (on the client host side)
* kill the drone process

Attach the output file for analysis

**Comment by pstavirs** [comment] 2018-01-18 13:31
@jimitsalvi never mind. I'm able to repro now. Will investigate and get back.

**Comment by jimitsalvi** [comment] 2018-01-19 16:40
@pstavirs - I see this issue with both interleaved and sequential streams.

**Comment by pstavirs** [comment] 2018-01-30 12:06
@jimitsalvi Please provide the console log as per the steps provided earlier _when using sequential streams_

**Comment by pstavirs** [comment] 2018-05-10 16:08
I found one issue when disabling the last interleaved streams would take a long time. I fixed it via e1194a1db38b4bdaf1586ddb0cbf6f45a37a6c64

Closing this as requested debug information was not received for investigation

**Closed by pstavirs** 2018-05-10 16:08 UTC
