### ISSUE TITLE
Please add to get interface name for windows 10 in the next version.

### ISSUE THREAD

**Issue by atmoskr** [pstavirs/ostinato#253] opened 2018-04-02 15:54 UTC
Windows 10 can change the interface name.
Accordingly, better to get this interface name so that we can use the name instead of complex NPF.

Port List
---------
0.\Device\NPF_{5DC599D8-819D-439F-820C-0F67D2DC7464} (Realtek USB NIC)
1.\Device\NPF_{B5FD6B9B-745A-4B8F-A744-FA8DDE873E37} (Oracle)
2.\Device\NPF_{B9ADFBDB-4A0D-49C9-8E42-D5F2CB6745C7} (Microsoft)
3.\Device\NPF_{61D411AE-9481-49DC-9FB5-A7FC62274DF4} (Realtek USB NIC)
4.\Device\NPF_{94440A10-1F5F-4DFB-A8D5-1C072FD981A9} (TAP-Win32 Adapter V9)
5.\Device\NPF_{FD768650-2835-4C64-99AF-F314D78EBF59} (Microsoft)

Thank you,
KM In.

**Comment by pstavirs** [comment] 2018-04-02 16:26
Duplicate of #222

**Closed by pstavirs** 2018-04-02 16:26 UTC
