### ISSUE TITLE
IPv4 packet - Specific payload won't send.

### ISSUE THREAD

**Issue by paulharris77** [pstavirs/ostinato#182] opened 2016-05-10 21:57 UTC
Ostinato won't send my required IPv4 packet shown below with a specific hex dump payload.

I have confirmed it is not sent with Wireshark running on the same PC as Ostinato and also a microcontroller set up to sniff broadcast packets on the network.

The issue can be reproduced by attempting to send a stream with a Frame Length (inc. FCS) set to 64 bytes (i.e. Ethernet minimum) and the following protocol settings:
![capture](https://cloud.githubusercontent.com/assets/10790952/15163891/2c959984-1703-11e6-8eda-b8a9ddbe93b1.PNG)
The issue seems to be around the 0x04 value of the second byte of the Hexdump payload, irrespective of the first payload byte's value or subsequent bytes.

If I set the second byte of payload to 0x00 or 0x01, the packet is picked up by Wireshark and the microcontroller.  If I set it to anything greater than 0x01 (e.g. 0x04), the packet is not detected by Wireshark or the microcontroller, but the Ostinato Statistics pane indicates that it thinks the frame was sent.

If I change the frame length to >=78 bytes (inc. FCS), the packet will send with second byte set to any value (including the problematic 0x04 value).

Can anyone reproduce the problem or explain if I am doing something wrong, it is not a valid packet (dropped by IP stack) or if it is a bug in Ostinato?

Thanks!

**Comment by pstavirs** [comment] 2016-05-11 14:31
Please save your problematic stream and attach it here so that we can try to recreate the problem.

**Comment by paulharris77** [comment] 2016-05-11 23:09
I have attached one stream file containing four streams (you might need to remove the .txt file extension that I had to add to get it to upload). 

[stream_for_debug.txt](https://github.com/pstavirs/ostinato/files/260367/stream_for_debug.txt)


There are two different pairs of streams.  Within each pair, there is one that works OK and one that is problematic and won't send.

The only difference between the OK stream and the problematic stream in each pair is the Frame Length (inc. FCS).  The problematic one is always 64 bytes long (with zero padding).  The length I have to increase the frame by to get the stream to send seems to vary depending on the value of the second byte of the payload which is very strange.

Thanks in advance for your help!

Paul

**Comment by pstavirs** [comment] 2016-05-12 15:55
I'm not able to reproduce the problem using your stream on Windows XP with Ostinato 0.7.1. I can see all 4 packets on Wireshark.

* What version and platform are you using?
* Are both Drone and Ostinato running on the same machine?
* And this is the same machine on which you are running Wireshark to confirm that packet is being sent out or not?
* How is the microcontroller connected to this machine? Directly via ethernet cable or via  switch/router?
* What is the IP payload? Are you trying to simulate some protocol or is it just user data?
* The IPv4 protocol is 0x00 - is that intentional?
* Wireshark interprets 0x00 as `IPv6 Hop-by-Hop extension` which of course is not valid for IPv4

**Comment by paulharris77** [comment] 2016-05-12 19:56
That is strange.  Please see below:

1) Windows 7 x86 SP1 with Ostinato 0.7.1
2) Yes
3) Yes
4) Microcontroller is connected via a switch.  I used broadcast MAC address to ensure the switch puts the packets out on all ports.  It is listen for any Ethernet frame and displays info on the frames when it receives them (e.g. dest/source addresses, length).  Just like Wireshark, the microcontroller doesn't receive the problem frames, but does receive the OK ones.
5) The data is a rudimentary "protocol" between the microcontroller and a Raspberry Pi.  The 0xFF is the start marker and the 0x0a the end marker.
6) The protocol in the IP header doesn't matter to me as it is a bespoke protocol

Thanks :)

**Comment by pstavirs** [comment] 2016-05-19 14:55
I tried on Windows 7, but not able to reproduce on that as well.

Can you try a different machine or a different NIC on the same machine?

**Comment by paulharris77** [comment] 2016-05-19 18:57
I only have the one NIC on the original PC. I will try another PC and get back to you. Thanks.

**Comment by paulharris77** [comment] 2016-05-29 21:47
Have got hold of another Windows 7 PC and likewise had no problems. Must be a NIC issue with the other PC. Any ideas as to what could cause it? Driver settings?

**Comment by pstavirs** [comment] 2016-05-30 14:37
Difficult to say what could be causing it on the other Win 7 PC.

I'm closing this issue for now.

**Closed by pstavirs** 2016-05-30 14:37 UTC
